//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrserver
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AFSInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AFSInfo()
        {
            this.transaction = new HashSet<transaction>();
            this.Colonka = new HashSet<Colonka>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        [JsonIgnore]
        public virtual Fuel_Reserve Fuel_Reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<transaction> transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Colonka> Colonka { get; set; }
    }
}
