//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_Reserve
    {
        public int Id { get; set; }
        public int type1 { get; set; }
        public int type2 { get; set; }
        public int type3 { get; set; }
        public int type4 { get; set; }
    
        public virtual AFSInfo AFSInfo { get; set; }
        public virtual fuel_data1 fuel_data1 { get; set; }
        public virtual fuel_data2 fuel_data2 { get; set; }
        public virtual fuel_data3 fuel_data3 { get; set; }
        public virtual fuel_data4 fuel_data4 { get; set; }
    }
}
