//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrserver
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class fuel_data1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fuel_data1()
        {
            this.Fuel_Reserve = new HashSet<Fuel_Reserve>();
        }

        public int id { get; set; }
        public string fuel_Type { get; set; }
        public decimal fuel_Price { get; set; }
        public int fuel_Amount { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Fuel_Reserve> Fuel_Reserve { get; set; }
    }
}
